### ISSUE TITLE
Not possible to override existing gems in item sockets

### ISSUE THREAD

**Issue by mbartosch** [Kristoferhh/WarlockSimulatorTBC#194]
It seems like it is not possible to change a socketed gem in a dedicated item.
Precondition: item sockets have been socketed.
Click on "Fill Item Sockets" -> "Fill all sockets" -> Current item slot -> *select a color*
Then select a different gem, click "Apply".
The original gem is still in the socket.

For now I work around this by exporting the JSON and manually changing the gem ID for the item, but it would be great if overriding socketed gems would work.

But anyway: this tool is absolutely awesome!

**Comment by Kristoferhh** [comment]
@mbartosch Hey, are you sure that you're selecting the correct options? Would you mind sending a screenshot of the options you select and which item's sockets you're expecting to change? It seems to be working fine for me :/

**Comment by mbartosch** [comment]
My bad, I totally overlooked the obvious and simple possibility to simply click on the gem in the currently selected item slot. (The above ticket was only about the "Fill Item Sockets" option.)
User error, sorry. Closing...
