### ISSUE TITLE
hi author is there any chance we can do the localization ? 

### ISSUE THREAD

**Issue by dabing1986** [Kristoferhh/WarlockSimulatorTBC#35]
Hi master 
this is a very  good simulation website. I wonder if there is any possibilities to do the localization  more specific from eng to Chinese .

**Comment by dabing1986** [comment]
Thanks a lot for the support we have a great group that also calculate the warlock simulation but it is in excel. so would be great to communicate once we have no language barrier:)

**Comment by dabing1986** [comment]
@Kristoferhh

**Comment by Kristoferhh** [comment]
Hey @dabing1986 I've added an option on the website to change the language to Chinese.
![image](https://user-images.githubusercontent.com/12117382/140333837-bdb2d807-40f3-4896-af3d-8bf6f9953ccf.png)
Only issue is that I don't speak Chinese ☹️ so if you can help with the translations then that would be great. There's a file here https://github.com/Kristoferhh/WarlockSimulatorTBC/blob/main/src/i18n/locales/zh/translations.json that handles all the translations.
If you want, you can just edit that file 
![image](https://user-images.githubusercontent.com/12117382/140335081-81ba6881-f46d-444d-84da-fe77881dbf9c.png)
 and then open a pull request to submit the changes and I'll approve them.
The file is just a JSON file where the format is like this ```"english sentence": "chinese sentence```. I've already added a few translations which I hope are correct 😅 so you should get the general idea.
Let me know if you have any questions/problems, I'll be happy to help 😃

**Comment by dabing1986** [comment]
Hi Kristoferhh  Thx a lot for the help I will check the translation . and if there is any error I will file a pull request 
<img width="376" alt="error" src="https://user-images.githubusercontent.com/48512053/140665606-4973cb09-5d76-4c2f-9cdd-df161945d52d.png">
BTW the website is not working right now once it come back I will share with my friend :)

**Comment by Kristoferhh** [comment]
@dabing1986 What browser are you using? Can you check if there's an update available? Maybe try using Google Chrome or Firefox?

**Comment by dabing1986** [comment]
@Kristoferhh  Thank a lot for the hint . I am using chrome right now . I think this is highly relevant to my VPN. Anyway I can see the website . I notice there are some minor translation missing. But no harm at all. the most important item translation is taking place :) I will create pull request for these minor translation issue.

**Comment by dabing1986** [comment]
one question for the translation 
If I want to translate this the format is as follows ? 


    "Iterations": "重复次数",
    "Min Fight Length: "最短战斗时长",
<img width="331" alt="Snipaste_2021-11-08_15-02-40" src="https://user-images.githubusercontent.com/48512053/140698254-96378b19-b979-4c4d-9723-bfed6915dc64.png">

**Comment by Kristoferhh** [comment]
Yep! That's correct 😃
