### ISSUE TITLE
Saved DPS - Sim All DPS Behavior Change

### ISSUE THREAD

**Issue by ifyouwouldplease** [Kristoferhh/WarlockSimulatorTBC#54]
Github Pages published version v1.0.4
Changes for "Sim All" DPS for the gear slot tabs:

- Last calculated DPS values not preserved after changing tabs
- Does not auto sort highest-to-lowest DPS after sim
- After change back to a tab, one previously calculated DPS is shown, but neither highest DPS from the sim nor the equipped item (maybe the last calc-ed/adjusted in sim all?)

**Comment by Kristoferhh** [comment]
Are the items not being sorted at all when you run sims? If so, what browser are you using and is it up to date?
I'll at least fix the issue with the dps values not saving tomorrow 👌

**Comment by ifyouwouldplease** [comment]
When I reported, the items did shuffle and sort high to low by DPS while the sim-all is running, but after the sim completed it went into a random order.
Now, as I type this with v1.0.7 the behavior is good on a single tab, sim-all completes and list is high to low by DPS; but if you change tabs and back there's only 1 arbitrary item that has a DPS value by it.
I normally run Firefox, and I did update it in the course of troubleshooting. The behavior happened in Chrome as well, with a new empty/minimal profile.

**Comment by Kristoferhh** [comment]
Ok I see what's happening, while the simulation is running, it's being correctly sorted and then once it finishes, it becomes unsorted.

**Comment by Kristoferhh** [comment]
This should be fixed now cd8ca8051d2a7a7f8f8708755f103c7c780a0bdc it was incorrectly only saving the *last* item's dps to the local storage when simulating all items.

**Comment by ifyouwouldplease** [comment]
Confirming that with v1.0.9 Github Pages "online" published version the issues I listed above are resolved, huge thanks, @Kristoferhh.
