### ISSUE TITLE
Error when trying to add gems to spellstrike hood

### ISSUE THREAD

**Issue by kboysen19** [Kristoferhh/WarlockSimulatorTBC#68]
I'm getting an error when I try to add any gems to spellstrike hood. Here's the error message:

![warlock sim error](https://user-images.githubusercontent.com/92343190/141515414-a7715723-08e1-4a37-8c87-d69ebe9a3cb6.jpg)

**Comment by Kristoferhh** [comment]
@kboysen19 Could you export your settings and copy paste them here? You can also PM me on discord if you'd prefer (Kristofer#8003)

**Comment by kboysen19** [comment]
{"auras":{"felArmor":true,"blessingOfKings":true,"blessingOfWisdom":true,"judgementOfWisdom":true,"markOfTheWild":true,"arcaneIntellect":true,"prayerOfFortitude":true,"prayerOfSpirit":true,"inspiringPresence":true,"powerOfTheGuardianWarlock":true,"curseOfTheElements":true,"shadowWeaving":true,"flaskOfPureDeath":true,"brilliantWizardOil":true,"blackenedBasilisk":true,"totemOfWrath":true,"manaSpringTotem":true},"selectedGems":{"head":{"24266":[null,null,null],"28963":[["meta",34220],["red",31867]]},"shoulders":{"21869":[["yellow",24050],["blue",24050]],"28967":[["yellow",31867],["blue",24056]]},"chest":{"21871":[["yellow",24050],["blue",24056]],"28964":[["red",31867],["yellow",31867],["yellow",31861]]},"bracer":{"24250":[["yellow",31861]]},"gloves":{"28780":[["yellow",31867],["blue",24056]]},"belt":{"24256":[["red",31867],["yellow",31861]]},"legs":{"24262":[["red",31867],["yellow",31867],["blue",31861]]},"boots":{"21870":[["yellow",31861],["blue",24056]]}},"selectedItems":{"twohand":22630,"head":24266,"neck":28762,"shoulders":28967,"back":22731,"chest":21871,"bracer":24250,"gloves":28780,"belt":24256,"legs":24262,"boots":21870,"ring1":28753,"ring2":28793,"trinket1":29370,"trinket2":27683,"wand":28673,"mainhand":0,"offhand":0},"talents":{"improvedHealthstone":2,"demonicEmbrace":5,"improvedVoidwalker":1,"felIntellect":3,"felDomination":1,"felStamina":3,"demonicAegis":3,"masterSummoner":2,"demonicSacrifice":1,"improvedShadowBolt":5,"bane":5,"devastation":5,"shadowburn":1,"intensity":2,"destructiveReach":2,"improvedImmolate":5,"ruin":1,"emberstorm":5,"backlash":3,"conflagrate":1,"shadowAndFlame":5,"suppression":0,"improvedCorruption":0,"improvedCurseOfWeakness":0,"improvedDrainSoul":0,"improvedLifeTap":0,"soulSiphon":0,"improvedCurseOfAgony":0,"felConcentration":0,"amplifyCurse":0,"grimReach":0,"nightfall":0,"empoweredCorruption":0,"shadowEmbrace":0,"siphonLife":0,"curseOfExhaustion":0,"shadowMastery":0,"contagion":0,"darkPact":0,"improvedHowlOfTerror":0,"malediction":0,"unstableAffliction":0,"improvedImp":0,"improvedHealthFunnel":0,"improvedSuccubus":0,"unholyPower":0,"improvedEnslaveDemon":0,"improvedFirestone":0,"manaFeed":0,"masterDemonologist":0,"demonicResilience":0,"soulLink":0,"demonicKnowledge":0,"demonicTactics":0,"summonFelguard":0,"cataclysm":0,"aftermath":0,"improvedFirebolt":0,"improvedLashOfPain":0,"improvedSearingPain":0,"pyroclasm":0,"netherProtection":0,"soulLeech":0,"shadowfury":0},"rotation":{"dot":{"immolate":false},"filler":{"searingPain":false,"shadowBolt":true,"incinerate":false},"curse":{"curseOfRecklessness":false,"curseOfDoom":false,"curseOfAgony":false,"curseOfTheElements":true},"finisher":{"shadowburn":true},"other":{}},"selectedEnchants":{"weapon":22749,"head":35447,"shoulders":24421,"back":25084,"chest":27960,"gloves":33997,"legs":31372,"boots":34008,"ring1":27924,"ring2":27924,"mainhand":22749},"settings":{"rotationOption":"simChooses","race":"human","iterations":"10000","min-fight-length":"180","max-fight-length":"600","target-level":"73","target-shadow-resistance":"0","target-fire-resistance":"0","fightType":"singleTarget","enemyAmount":"5","automatically-open-sim-details":"yes","randomizeValues":"no","infinitePlayerMana":"no","infinitePetMana":"no","petChoice":"2","sacrificePet":"yes","petMode":"0","prepopBlackBook":"no","shattrathFaction":"Aldor","shattrathFactionReputation":"no","lashOfPainUsage":"noISB","enemyArmor":"7700","improvedCurseOfTheElements":"0","powerInfusionAmount":"1","bloodlustAmount":"1","innervateAmount":"1","improvedDivineSpirit":"0","mageAtieshAmount":"1","warlockAtieshAmount":"1","totemOfWrathAmount":"1","ferociousInspirationAmount":"1","improvedWrathOfAirTotem":"no","shadowPriestDps":"1000","improvedImpSetting":"0","improvedFaerieFire":"no","improvedExposeArmor":"0","survivalHunterAgility":"1000","exposeWeaknessUptime":"90","customIsbUptime":"yes","customIsbUptimeValue":"50"}}

**Comment by kboysen19** [comment]
Not sure if this is helpful info or not but I'm also getting the error if I just try to sim with spellstrike hood equipped and no gems in it

**Comment by Kristoferhh** [comment]
Refresh the page and try again, should be fixed now 🙂 #69 sorry for the inconvenience

**Comment by kboysen19** [comment]
No worries at all, thanks for the quick fix!
