### ISSUE TITLE
hi,it not work,please help me

### ISSUE THREAD

**Issue by Forchunming** [Kristoferhh/WarlockSimulatorTBC#74]
it give me a error,when i use it today

kristoferhh.github.io 显示
Error: Uncaught Type Error: S(...),tablesorter is not a function
URL: https://kristoferhh.github.io/WarlockSimulatorTBC/static/js/
2.1f3828db.chunk.js
Line Number: 2
Please report this to Kristofer#8003 on Discord or create an issue
at https://github.com/Kristoferhh/WarlockSimulatorTBC.

**Comment by Kristoferhh** [comment]
Hey @Forchunming , try disabling your browser extensions if you have any installed. I'll take a better look at this tomorrow and try to fix it 🙂

**Comment by Kristoferhh** [comment]
This should be fixed now #80 let me know if you continue getting this error.
